# Generated by Django 4.1.3 on 2022-12-11 18:15

from django.db import migrations, models
import django.db.models.deletion

import os
import json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    def insert_init_data(apps, schema_editor):
        my_path = os.path.abspath(os.path.dirname(__file__))
        parent_path = os.path.abspath(os.path.join(my_path, os.pardir))

        with open(os.path.join(parent_path, 'static/data/mammamiadata.json')) as file:
            file = json.load(file)

        df = file

        Pizza = apps.get_model('mammamiaapp', 'Pizza')
        TipoMasa = apps.get_model('mammamiaapp', 'TipoMasa')
        Ingrediente = apps.get_model('mammamiaapp', 'Ingrediente')

        for i in df:
            if i['model'] == 'mammamiaapp.tipomasa':
                TipoMasa.objects.create(pk = i['pk'], nombre = i['fields']['nombre'])

        for i in df:
            if i['model'] == 'mammamiaapp.ingrediente':
                Ingrediente.objects.create(pk = i['pk'], nombre = i['fields']['nombre'])

        for i in df:
            if i['model'] == 'mammamiaapp.pizza':

                newPizza = Pizza.objects.create(pk = i['pk'], nombre = i['fields']['nombre'], tipoMasa = TipoMasa.objects.get(pk = i['fields']['tipoMasa']), precio = i['fields']['precio'])

                ingredientesPizza = []
                for y in i['fields']['ingredientes']:
                    ingredientesPizza.append(Ingrediente.objects.get(pk = y))

                newPizza.ingredientes.set(ingredientesPizza)
                ingredientesPizza.clear()
        
        

        pass

    def undo_insert_data(apps, schema_editor):
        Pizza = apps.get_model('mammamiaapp', 'Pizza')
        TipoMasa = apps.get_model('mammamiaapp', 'TipoMasa')
        Ingrediente = apps.get_model('mammamiaapp', 'Ingrediente')

        Pizza.objects.all().delete()
        TipoMasa.objects.all().delete()
        Ingrediente.objects.all().delete()
        pass

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('ingredientes', models.ManyToManyField(to='mammamiaapp.ingrediente')),
                ('tipoMasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mammamiaapp.tipomasa')),
            ],
        ),

        migrations.RunPython(insert_init_data, reverse_code=undo_insert_data)
    ]
